/*:
Inkport.js

@plugindesc imports story.json generated by ink into usable data for RMMV. JS port by y-lohse
@author levente

  * @param Story File
  * @desc The file where the Ink story lives. Located in data folder.
  * Default:
  * @default
  * @require 1
  * @dir data/
  * @type file

@help put your .json file generated by ink into your data folder of the game.

*/

var Inkport = Inkport || {};
Inkport.Parameters = PluginManager.parameters('Inkport');
Inkport.StoryFile = String(Inkport.Parameters["Story File"]);

(function() {

	var story;
  var storyContainer = document.querySelectorAll('#story')[0];

	fetch('story.json')
	.then(function(response){
		return response.text();
	})
	.then(function(storyContent){
		story = new inkjs.Story(storyContent);
		continueStory();
	});

    function continueStory() {

        var paragraphIndex = 0;
        var delay = 0.0;

        // Generate story text - loop through available content
        while(story.canContinue) {

            // Get ink to generate the next paragraph
            var paragraphText = story.Continue();

            // Create paragraph element
            var paragraphElement = document.createElement('p');
            paragraphElement.innerHTML = paragraphText;
            storyContainer.appendChild(paragraphElement);

        }

        // Create HTML choices from ink choices
        story.currentChoices.forEach(function(choice) {

            // Create paragraph with anchor element
            var choiceParagraphElement = document.createElement('p');
            choiceParagraphElement.classList.add("choice");
            choiceParagraphElement.innerHTML = `<a href='#'>${choice.text}</a>`
            storyContainer.appendChild(choiceParagraphElement);

            // Fade choice in after a short delay
            showAfter(delay, choiceParagraphElement);
            delay += 200.0;

            // Click on choice
            var choiceAnchorEl = choiceParagraphElement.querySelectorAll("a")[0];
            choiceAnchorEl.addEventListener("click", function(event) {

                // Don't follow <a> link
                event.preventDefault();

                // Remove all existing choices
                var existingChoices = storyContainer.querySelectorAll('p.choice');
                for(var i=0; i<existingChoices.length; i++) {
                    var c = existingChoices[i];
                    c.parentNode.removeChild(c);
                }

                // Tell the story where to go next
                story.ChooseChoiceIndex(choice.index);

                // Aaand loop
                continueStory();
            });
        });
    }

})();
